bin.includes = META-INF/,\
               libs/apiguardian/apiguardian-api-1.1.2.jar,\
               libs/hamcrest/hamcrest-3.0.jar,\
               libs/junit/junit-jupiter-api-6.1.0.jar,\
               libs/junit/junit-jupiter-engine-6.1.0.jar,\
               libs/junit/junit-jupiter-params-6.1.0.jar,\
               libs/junit/junit-platform-commons-6.1.0.jar,\
               libs/junit/junit-platform-engine-6.1.0.jar,\
               libs/junit/junit-platform-launcher-6.1.0.jar,\
               libs/junit/junit-platform-suite-api-6.1.0.jar,\
               libs/junit/junit-platform-suite-engine-6.1.0.jar,\
               libs/opentest4j/opentest4j-1.3.0.jar
