bin.includes = META-INF/,\
               libs/appium/java-client-10.0.0.jar,\
               libs/hamcrest-core/hamcrest-core-1.3.jar,\
               libs/junit/junit-4.12.jar,\
               libs/slf4j/slf4j-api-2.0.12.jar,\
               libs/selenium/auto-service-annotations-1.1.1.jar,\
               libs/selenium/byte-buddy-1.18.5.jar,\
               libs/selenium/error_prone_annotations-2.41.0.jar,\
               libs/selenium/failureaccess-1.0.3.jar,\
               libs/selenium/guava-33.5.0-jre.jar,\
               libs/selenium/j2objc-annotations-3.1.jar,\
               libs/selenium/jspecify-1.0.0.jar,\
               libs/selenium/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar,\
               libs/selenium/opentelemetry-api-1.59.0.jar,\
               libs/selenium/opentelemetry-common-1.59.0.jar,\
               libs/selenium/opentelemetry-context-1.59.0.jar,\
               libs/selenium/opentelemetry-exporter-logging-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-common-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-extension-autoconfigure-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-extension-autoconfigure-spi-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-logs-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-metrics-1.59.0.jar,\
               libs/selenium/opentelemetry-sdk-trace-1.59.0.jar,\
               libs/selenium/selenium-api-4.41.0.jar,\
               libs/selenium/selenium-chrome-driver-4.41.0.jar,\
               libs/selenium/selenium-chromium-driver-4.41.0.jar,\
               libs/selenium/selenium-devtools-v143-4.41.0.jar,\
               libs/selenium/selenium-devtools-v144-4.41.0.jar,\
               libs/selenium/selenium-devtools-v145-4.41.0.jar,\
               libs/selenium/selenium-edge-driver-4.41.0.jar,\
               libs/selenium/selenium-firefox-driver-4.41.0.jar,\
               libs/selenium/selenium-http-4.41.0.jar,\
               libs/selenium/selenium-ie-driver-4.41.0.jar,\
               libs/selenium/selenium-java-4.41.0.jar,\
               libs/selenium/selenium-json-4.41.0.jar,\
               libs/selenium/selenium-manager-4.41.0.jar,\
               libs/selenium/selenium-os-4.41.0.jar,\
               libs/selenium/selenium-remote-driver-4.41.0.jar,\
               libs/selenium/selenium-safari-driver-4.41.0.jar,\
               libs/selenium/selenium-support-4.41.0.jar
