# Timeouts
# To load pages
#timeoutToOpenPage=30
# General
#timeout=600
# To service initialization (default 1200)
#timeoutServiceInitialization=1200

# Topology
applications=\
	ca;https://ca-web.com

# Test environment specific scenario data
environment=ca-prod