browser=Firefox
browserPath=C:/Users/Public/itestcloud/browsers/Firefox.app/Contents/MacOS/firefox
browserDriver=C:/Users/Public/itestcloud/drivers/geckodriver
browserProfile=C:/Users/Public/itestcloud/profiles/firefox
